---
title: "project1"
author: "grace brooks"
date: "2024-09-10"
output: html_document
---

### Install 'tidyverse'

```{r,eval=FALSE}
##Install the tidyverse package if you dont have it
if (!require("tidyverse", quietly = TRUE)) {
    install.packages("tidyverse")
}
```

```{r,message=FALSE}
library("tidyverse")
```
# data
```{r}
library("here")
library("tidyverse")

# tests if a directory named "data" exists locally
if (!dir.exists(here("data"))) {
    dir.create(here("data"))
}

# saves data only once (not each time you knit a R Markdown)
if (!file.exists(here("data", "chocolate.RDS"))) {
    url_csv <- "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-18/chocolate.csv"
    chocolate <- readr::read_csv(url_csv)

    # save the file to RDS objects
    saveRDS(chocolate, file = here("data", "chocolate.RDS"))
}
```
```{r}
chocolate <- readRDS(here("data", "chocolate.RDS")) 
as_tibble(chocolate)

glimpse(chocolate)
```
# part one: explore data

```{r}         
library("dplyr", "ggplot2") #histograms of ratings
hist(chocolate$rating)
hist(chocolate$rating, breaks=10) 
hist(chocolate$rating, breaks=15)
hist(chocolate$rating, breaks=20) 
hist(chocolate$rating, breaks=25)
#changing the number of bins determines the widths and number of bars in the histogram by changing the intervals that the data can fall into. I think that 15 bins looks the best as I think that you can see the trends best. This plot allows you to easily see the break in ratings between 3.0 and roughly 3.25 which is harder to see in smaller plots, and personally broken up too much in the plots with more bins.

#consider the countries where the beans originated from. How many reviews come from each country of bean origin?
table(chocolate$country_of_bean_origin)
#what is average rating score from reviews of chocolate bars that have ecuador as the country of bean origin? for the same data set of reviews, also calculate the number of reviews and the standard deviation of the rating scores. Answer should be a new data frame with 3 summary statistics in 3 columns. Label the name of these columns mean, sd, and total.
ecuador <- filter(chocolate, country_of_bean_origin =="Ecuador")
meanec <- mean(ecuador$rating) 
sdec <- sd(ecuador$rating) 
totalec <- nrow(ecuador) 
summary_stats_ecuador <- data.frame(mean = meanec, sd = sdec, total = totalec ) 
glimpse(summary_stats_ecuador) 
#which company (name) makes the best chocolates with beans from ecuador? 
ecuador %>% group_by(company_manufacturer) %>% summarise(max = max(rating))
#the code above summarizes the best chocolates made from beans from ecuador by the manufacturer name, based upon rating. This shows us that A. Morin makes the best chocolates with beans from ecuador with a rating of 3.75.

#calculate the average rating across all country of origins for beans. Which top 3 countries (for bean origin) have the highest ratings on average? 
chocolate %>% group_by(country_of_bean_origin) %>% summarise(mean = mean(rating)) %>% arrange(desc(mean)) 
# the three highest ratings on average are Tobago with a mean of 3.62, China with a mean of 3.5, and Sao Tome & Principe with mean of 3.5

#Remove any countries with less than 10 reviews, then determine which 3 countries have the highest reviews 
chocolate %>% group_by(country_of_bean_origin) %>% filter(n()>10) %>% summarise(mean = mean(rating)) %>% arrange(desc(mean)) 
#when the countries with less than 10 reviews are removed the three highest ratings on average become Congo with mean of 3.32, Cuba with mean of 3.29, and Vietnam with mean of 3.29.

#explore relationship between percent chocolate and ratings 

#remove countries with less than 50 reviews 
morethan50 <- chocolate %>% group_by(country_of_bean_origin) %>% filter(n()>50) 
#add columngrouping by chocolate percentage and re-order 
morethan50 <- mutate(morethan50, percent_groups = case_when(  
    (substr(cocoa_percent,1,1)=="1" ~ "<60%"),
    (substr(cocoa_percent,1,1)== "2" ~ "<60%"),
    (substr(cocoa_percent,1,1)== "3" ~ "<60%"),
    (substr(cocoa_percent,1,1)== "4" ~ "<60%"),
    (substr(cocoa_percent,1,1)== "5" ~ "<60%"),
    (substr(cocoa_percent,1,1)=="6" ~ ">60-<70%"),
    (substr(cocoa_percent,1,1)=="7" ~ ">70-<90%"),
    (substr(cocoa_percent,1,1)=="8" ~ ">70-<90%"),
    (substr(cocoa_percent,1,1)=="9" ~ ">= 90%") ))

morethan50 %>% group_by(country_of_bean_origin) %>% reframe(percent_groups) %>% arrange(percent_groups) 
#for each country make 4 boxplots plotting each group -> groups on x axis and ratings on y axis 
library(ggplot2) 
ggplot(morethan50, aes(x=percent_groups, y=rating)) + geom_boxplot() + facet_wrap(~country_of_bean_origin) 
#on average it seems like the 70-90% group has the highest ratings, which seems to be agreed upon by most countries
```

# part two: joining two datasets together

```{r}         
library(gapminder) 
gapminder_unique <- unique(gapminder)
chocolate_merged <- left_join(chocolate, gapminder_unique[,1:2], by=c("country_of_bean_origin"="country")) 
ggplot(chocolate_merged, aes(x=continent, y=rating)) + geom_violin()
```

# part three: convert wide data into long data

```{r}         
chocolate_sum <-mutate(chocolate, beans = str_detect(chocolate$ingredients, "B")) %>% mutate(chocolate, sugar = str_detect(chocolate$ingredients, "S,|S$")) %>% mutate(chocolate, cocoa_butter = str_detect(chocolate$ingredients, "C")) %>% mutate(chocolate, vanilla = str_detect(chocolate$ingredients, "V")) %>% mutate(chocolate, letchin = str_detect(chocolate$ingredients, "L")) %>% mutate(chocolate, salt = str_detect(chocolate$ingredients, "Sa"))

chocolate_sum$beans <- ifelse(chocolate_sum$beans == "TRUE", 1,0)
chocolate_sum$sugar <- ifelse(chocolate_sum$sugar == "TRUE", 1,0)
chocolate_sum$cocoa_butter <- ifelse(chocolate_sum$cocoa_butter == "TRUE", 1,0) 
chocolate_sum$vanilla <- ifelse(chocolate_sum$vanilla == "TRUE", 1,0) 
chocolate_sum$letchin <- ifelse(chocolate_sum$letchin == "TRUE", 1,0) 
chocolate_sum$salt <- ifelse(chocolate_sum$salt == "TRUE",1,0)

chocolate_sum$beans[is.na(chocolate_sum$beans)] <- 0
chocolate_sum$sugar[is.na(chocolate_sum$sugar)] <- 0
chocolate_sum$cocoa_butter[is.na(chocolate_sum$cocoa_butter)] <- 0
chocolate_sum$vanilla[is.na(chocolate_sum$vanilla)] <- 0
chocolate_sum$letchin[is.na(chocolate_sum$letchin)] <- 0
chocolate_sum$salt[is.na(chocolate_sum$salt)] <- 0

chocolate_sum <- mutate(chocolate_sum, char_cocoa = str_detect(chocolate$most_memorable_characteristics, "cocoa")) %>% mutate(chocolate_sum, char_sweet = str_detect(chocolate_sum$most_memorable_characteristics,"sweet")) %>% mutate(chocolate_sum, char_nutty = str_detect(chocolate_sum$most_memorable_characteristics, "nutty")) %>% mutate(chocolate_sum, char_creamy = str_detect(chocolate_sum$most_memorable_characteristics, "creamy")) %>% mutate(chocolate_sum, char_roasty = str_detect(chocolate_sum$most_memorable_characteristics, "roasty")) %>% mutate(chocolate_sum, char_earthy = str_detect(chocolate_sum$most_memorable_characteristics, "earthy"))

chocolate_sum$char_cocoa <- ifelse(chocolate_sum$char_cocoa == "TRUE", 1,0) 
chocolate_sum$char_sweet <- ifelse(chocolate_sum$char_sweet == "TRUE", 1,0) 
chocolate_sum$char_nutty <- ifelse(chocolate_sum$char_nutty == "TRUE", 1,0)
chocolate_sum$char_creamy <- ifelse(chocolate_sum$char_creamy == "TRUE", 1,0) 
chocolate_sum$char_roasty <- ifelse(chocolate_sum$char_roasty == "TRUE", 1,0)
chocolate_sum$char_earthy <- ifelse(chocolate_sum$char_earthy == "TRUE", 1,0)

chocolate_sum <- chocolate_sum[-c(1,2,3,5,6,7,8,9,10)]

chocolate_sum %>% group_by(review_date) %>% summarise(beans = mean(beans), sugar = mean(sugar), cocoa_butter = mean(cocoa_butter), vanilla = mean(vanilla), letchin = mean(letchin), salt = mean(salt), char_cocoa = mean(char_cocoa), char_sweet = mean(char_sweet), char_nutty = mean(char_nutty), char_creamy = mean(char_creamy), char_roasty = mean(char_roasty), char_earthy = mean(char_earthy))

chocolate_sum_avgs <- chocolate_sum %>% group_by (review_date) %>% summarise(beans = mean(beans), sugar = mean(sugar), cocoa_butter = mean(cocoa_butter), vanilla = mean(vanilla), letchin = mean(letchin), salt = mean(salt), char_cocoa = mean(char_cocoa), char_sweet = mean(char_sweet), char_nutty = mean(char_nutty), char_creamy = mean(char_creamy), char_roasty = mean(char_roasty), char_earthy = mean(char_earthy))

chocolate_sum_avgs_long <- chocolate_sum_avgs %>% pivot_longer(cols = c('beans', 'sugar', 'cocoa_butter', 'vanilla', 'letchin', 'salt', 'char_cocoa', 'char_sweet', 'char_nutty', 'char_creamy', 'char_roasty', 'char_earthy'), names_to = 'feature', values_to = 'mean_score') 
```

# part four: data visualization

```{r}         
ggplot(chocolate_sum_avgs_long, aes(x=review_date, y=mean_score)) + geom_point() + geom_smooth() + labs(title = "Average Use of Factors Over Time", subtitle = "Most factors remain relatively steady, however letchin and vanila sharply decline in use", caption = "Grace Brooks", x = "Review Date in Years", y = "Average Score") + facet_wrap(~feature) 
```

# part five: make the worst plot you can!

```{r}         
ggplot(chocolate, aes(x=review_date, y=company_manufacturer)) + geom_point(size = 10) + labs(title = "comp rev") + geom_smooth() + facet_wrap(~ingredients) 
# why the plot is bad:
#- The plot is poorly titled, it does not tell anything about what the graph is saying. In the future, naming a plot in a way that will tell us something about the data and what is being shown will help.
#- The axis are not titled, it just has variable names which is not clean. To make a plot better, the axis should be titled beyond the variable names given to clarity and clean the plot.
#- y axis is not filtered at all, too many options makes it difficult to read. Future plots should take some values out of the data, or more the sclae around to make it readable.
#- points are too big, so they cannot be differentiated. The scale of the points should be changed so that the points do not run together and patterns can be visualized.
#- variables that are used are not actually helpful for anything. Looking at company manufacturer name in comparison to review date does not tell any information at all. Even if you wanted some connection between these variables, a box plot would not be the best option.
#- regression line added created many warnings and is not telling of anything. In the future, plots should be looked into before adding a line. In this case, almost every y axis point had a review date associated with it, which makes the pattern almost grid like. This makes the regression line almost impossible to fix. In the future, points and data should be looked into before haphazardly adding a regression line
#-facet wrap used is again unrelated to the variables being shown. Additionally, because of the way the ingredients data is presented you cannot really tell what each is without specific notes. In the future, one should not facet wrap when the variables are not cleaned and do not make sense.
```

# part six: make my plot better!

```{r}         
chocolate %>% ggplot(aes( x = as.factor(review_date), y = rating)) +
geom_violin(width = 1.5) + labs(title = "Distributions of Ratings by
Year of Review", subtitle = "This plot looks at the distribution of the
Chocolate Ratings by the Years of Review", x = "Year of Review", y =
"Chocolate Rating") + geom_boxplot(width=0.1, color = "red") +
theme_classic() 
# how plot was improved:
#- The title was added to describe what the graph was exploring.
#- A subtitle was also added to describe a little bit more about the goals of the plot
#- Axis titles were added to clarify more beyond just the variable name, this is also a cleaner look than the variable names with underscores.
#- I removed the fill because while the color was pretty, it did not add to the plot at all, it just told the same thing as the x-axis
#-I added a boxplot within each violin plot section to allow the quartiles, median, and outliers to be seen more clearly. I made these red to stick out more.
#- I changed the theme to "classic" which made the whole plot look cleaner
#- I increased the width of the violins in the plot to make it easier to tell where more values lie
```